from __future__ import annotations

from autonomous_betting_agent import magazine_sale_ready_patch_impl as _impl

_impl._APPLIED_FLAG = "_ABA_SALE_READY_DIRECT_MULTI_LEG_APPLIED"

apply_magazine_sale_ready_patch = _impl.apply_magazine_sale_ready_patch
sale_ready_chain_items = _impl.sale_ready_chain_items
sale_ready_team_items = _impl.sale_ready_team_items
sale_ready_injury_items = _impl.sale_ready_injury_items
sale_ready_matchup_items = _impl.sale_ready_matchup_items
sale_ready_risk_items = _impl.sale_ready_risk_items
sale_ready_recommendation = _impl.sale_ready_recommendation
translate_country_name = _impl.translate_country_name
translate_team_label = _impl.translate_team_label
translate_event_name = _impl.translate_event_name
translate_country_terms_in_text = _impl.translate_country_terms_in_text
